FROM alpine:latest

RUN apk update
RUN apk add g++ g++-aarch64-none-elf py3-pip cmake make pkgconf ninja gdb
RUN pip install --break-system-packages meson
RUN apk add ffmpeg-dev sdl2-dev sqlite-dev openssl-dev boost-dev libxkbcommon
RUN apk add sudo

RUN echo "ALL ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
